# Generated by Django 2.0.7 on 2018-08-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Token',
        ),
    ]
